Repository jhipster/jhipster.github.io, pull requests merged in 2021-03, with the labels that each got.

#1089 Added "See also" sections to the JDL app options and regular options pages
  pages/jdl/applications.md
  pages/jdl/options.md
Labels: JDL

#1086 Update Cassandra JDL types
  pages/jdl/entities.md
Labels: next-release, v7

#1069 Remove UAA
  _layouts/default.html
  pages/api-gateway.md
  pages/common-application-properties.md
  pages/creating_an_app.md
  pages/docker_compose.md
  pages/jdl/applications.md
  pages/microservices_architecture.md
  pages/security.md
  pages/team.md
  pages/user-entity.md
Labels: next-release, v7

#1076 CI/CD Add Cypress Dashboard documentation
  pages/setting_up_ci.md
Labels: next-release, v7

#1088 Upgrade the blueprint documentation to JHipster 7
  modules/creating_a_blueprint.md
Labels: next-release, v7

#1095 Remove traefik
  _layouts/default.html
  pages/common-ports.md
  pages/jdl/deployments.md
  pages/jdl/getting-started.md
  pages/microservices_architecture.md
  pages/production.md
  pages/separating-front-end-and-api.md
  pages/tech_stack.md
  pages/traefik.md
Labels: next-release, v7

#1098 Add section about embedded documents for Couchbase and MongoDB
  pages/managing_relationships.md
Labels: next-release

#1030 Remove passages for context path configuration in production build section
  pages/production.md
Labels: next-release
